# Generated by Django 3.0.7 on 2020-06-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregar', '0003_auto_20200610_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='entregar.Tag'),
        ),
    ]
