# Generated by Django 3.0.7 on 2020-06-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregar', '0004_auto_20200611_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Levar', 'Levar'), ('Comer Aqui ', 'Comer Aqui')], max_length=200, null=True),
        ),
    ]
