# Generated by Django 3.0.7 on 2020-06-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregar', '0005_auto_20200614_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='notes',
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
