# Generated by Django 3.0.7 on 2020-06-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregar', '0008_customer_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='produto_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
