# Generated by Django 3.0.7 on 2020-06-19 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entregar', '0009_product_produto_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='produto_pic',
        ),
    ]
