# Generated by Django 3.0.7 on 2020-06-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregar', '0012_auto_20200624_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='celular',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='nome',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
