# Generated by Django 3.0.7 on 2020-06-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregar', '0013_auto_20200624_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Foto_de_Perfil',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='nome',
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='HambC.png', null=True, upload_to=''),
        ),
    ]
